package modelo;
// Generated 15-dic-2019 17:47:27 by Hibernate Tools 4.3.1



/**
 * BonificacionId generated by hbm2java
 */
public class BonificacionId  implements java.io.Serializable {


     private int codemp;
     private String mes;

    public BonificacionId() {
    }

    public BonificacionId(int codemp, String mes) {
       this.codemp = codemp;
       this.mes = mes;
    }
   
    public int getCodemp() {
        return this.codemp;
    }
    
    public void setCodemp(int codemp) {
        this.codemp = codemp;
    }
    public String getMes() {
        return this.mes;
    }
    
    public void setMes(String mes) {
        this.mes = mes;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BonificacionId) ) return false;
		 BonificacionId castOther = ( BonificacionId ) other; 
         
		 return (this.getCodemp()==castOther.getCodemp())
 && ( (this.getMes()==castOther.getMes()) || ( this.getMes()!=null && castOther.getMes()!=null && this.getMes().equals(castOther.getMes()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodemp();
         result = 37 * result + ( getMes() == null ? 0 : this.getMes().hashCode() );
         return result;
   }   


}


