package modelo;
// Generated 15-dic-2019 17:47:27 by Hibernate Tools 4.3.1

/**
 * Bonificacion generated by hbm2java
 */
public class Bonificacion implements java.io.Serializable {

    private BonificacionId id;
    private Empleado empleado;
    private Float importebonificado;

    public Bonificacion() {

    }

    public Bonificacion(BonificacionId id, Empleado empleado) {
        this.id = id;
        this.empleado = empleado;
    }

    public Bonificacion(BonificacionId id, Empleado empleado, Float importebonificado) {
        this.id = id;
        this.empleado = empleado;
        this.importebonificado = importebonificado;
    }

    public BonificacionId getId() {
        return this.id;
    }

    public void setId(BonificacionId id) {
        this.id = id;
    }

    public Empleado getEmpleado() {
        return this.empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    public Float getImportebonificado() {
        return this.importebonificado;
    }

    public void setImportebonificado(Float importebonificado) {
        this.importebonificado = importebonificado;
    }

}
