package modelo;
// Generated 15-dic-2019 17:47:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int codemp;
     private String nomemp;
     private Float salario;
     private Set reparacions = new HashSet(0);
     private Set bonificacions = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(int codemp, String nomemp) {
        this.codemp = codemp;
        this.nomemp = nomemp;
    }
    public Empleado(int codemp, String nomemp, Float salario, Set reparacions, Set bonificacions) {
       this.codemp = codemp;
       this.nomemp = nomemp;
       this.salario = salario;
       this.reparacions = reparacions;
       this.bonificacions = bonificacions;
    }
   
    public int getCodemp() {
        return this.codemp;
    }
    
    public void setCodemp(int codemp) {
        this.codemp = codemp;
    }
    public String getNomemp() {
        return this.nomemp;
    }
    
    public void setNomemp(String nomemp) {
        this.nomemp = nomemp;
    }
    public Float getSalario() {
        return this.salario;
    }
    
    public void setSalario(Float salario) {
        this.salario = salario;
    }
    public Set getReparacions() {
        return this.reparacions;
    }
    
    public void setReparacions(Set reparacions) {
        this.reparacions = reparacions;
    }
    public Set getBonificacions() {
        return this.bonificacions;
    }
    
    public void setBonificacions(Set bonificacions) {
        this.bonificacions = bonificacions;
    }

    @Override
    public String toString() {
        return codemp + " - " + nomemp;
    }




}


