package modelo;
// Generated 15-dic-2019 17:47:27 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Reparacion generated by hbm2java
 */
public class Reparacion implements java.io.Serializable {

    private ReparacionId id;
    private Coche coche;
    private Empleado empleado;
    private Double importe;
    private Date fechaf;

    public Reparacion() {
    }

    public Reparacion(ReparacionId id, Coche coche, Empleado empleado) {
        this.id = id;
        this.coche = coche;
        this.empleado = empleado;
    }

    public Reparacion(ReparacionId id, Coche coche, Empleado empleado, Double importe, Date fechaf) {
        this.id = id;
        this.coche = coche;
        this.empleado = empleado;
        this.importe = importe;
        this.fechaf = fechaf;
    }

    public ReparacionId getId() {
        return this.id;
    }

    public void setId(ReparacionId id) {
        this.id = id;
    }

    public Coche getCoche() {
        return this.coche;
    }

    public void setCoche(Coche coche) {
        this.coche = coche;
    }

    public Empleado getEmpleado() {
        return this.empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    public Double getImporte() {
        return this.importe;
    }

    public void setImporte(Double importe) {
        this.importe = importe;
    }

    public Date getFechaf() {
        return this.fechaf;
    }

    public void setFechaf(Date fechaf) {
        this.fechaf = fechaf;
    }

}
