package modelo;
// Generated 15-dic-2019 17:47:27 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * ReparacionId generated by hbm2java
 */
public class ReparacionId implements java.io.Serializable {

    private int codemp;
    private String matricula;
    private Date fechai;

    public ReparacionId() {
    }

    public ReparacionId(int codemp, String matricula, Date fechai) {
        this.codemp = codemp;
        this.matricula = matricula;
        this.fechai = fechai;
    }

    public int getCodemp() {
        return this.codemp;
    }

    public void setCodemp(int codemp) {
        this.codemp = codemp;
    }

    public String getMatricula() {
        return this.matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    public Date getFechai() {
        return this.fechai;
    }

    public void setFechai(Date fechai) {
        this.fechai = fechai;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof ReparacionId)) {
            return false;
        }
        ReparacionId castOther = (ReparacionId) other;

        return (this.getCodemp() == castOther.getCodemp())
                && ((this.getMatricula() == castOther.getMatricula()) || (this.getMatricula() != null && castOther.getMatricula() != null && this.getMatricula().equals(castOther.getMatricula())))
                && ((this.getFechai() == castOther.getFechai()) || (this.getFechai() != null && castOther.getFechai() != null && this.getFechai().equals(castOther.getFechai())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getCodemp();
        result = 37 * result + (getMatricula() == null ? 0 : this.getMatricula().hashCode());
        result = 37 * result + (getFechai() == null ? 0 : this.getFechai().hashCode());
        return result;
    }

    @Override
    public String toString() {
        return matricula + " - " + fechai;
    }

}
